version: "3.8"
services:
  nextjs:
    image: ${DOCKER_USERNAME}/${APP_NAME}:latest
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
      - SENDER_EMAIL=${SENDER_EMAIL}
    networks:
      - coolify
    labels:
      - "coolify.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.geniesolaire.rule=Host(`wc0css4sk4o0848ogk8ss08g.195.35.48.112.sslip.io`)"
      - "traefik.http.routers.geniesolaire.entrypoints=http"
      - "traefik.http.services.geniesolaire.loadbalancer.server.port=3000"
      - "traefik.docker.network=coolify"
    expose:
      - "3000"
    container_name: geniesolaire
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  coolify:
    external: true
