version: "3.8"
services:
  nextjs:
    image: ${DOCKER_USERNAME}/${APP_NAME}:latest
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
      - SENDER_EMAIL=${SENDER_EMAIL}
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`wc0css4sk4o0848ogk8ss08g.195.35.48.112.sslip.io`)"
      - "traefik.http.routers.${APP_NAME}.entrypoints=web,websecure"
      - "traefik.http.services.${APP_NAME}-svc.loadbalancer.server.port=3000"
      - "traefik.http.routers.${APP_NAME}.service=${APP_NAME}-svc"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.middlewares.${APP_NAME}-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  traefik-public:
    external: true
