version: "3.8"
services:
  nextjs:
    image: ${DOCKER_USERNAME}/${APP_NAME}:latest
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=80
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
      - SENDER_EMAIL=${SENDER_EMAIL}
    ports:
      - "80:80"
    networks:
      - nginx-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`wc0css4sk4o0848ogk8ss08g.195.35.48.112.sslip.io`)"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${APP_NAME}.tls=true"
    # Vous pouvez ajouter des labels pour le reverse proxy, par exemple :
    # labels:
    #   - "VIRTUAL_HOST=www.mondomaine.com"
    #   - "LETSENCRYPT_HOST=www.mondomaine.com"

networks:
  nginx-proxy:
    external: true
