name: Deploy to CapRover
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install CapRover CLI
        run: |
          npm install -g caprover@latest
          caprover --version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:latest

      - name: Deploy to CapRover
        run: |
          # Installation de la dernière version de CapRover CLI
          npm install -g caprover@latest

          # Configuration du déploiement avec l'URL nip.io
          caprover deploy \
          --caproverUrl "https://captain.195.35.48.112.nip.io" \
          --appToken "${{ secrets.CAPROVER_APP_TOKEN }}" \
          --imageName "${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:latest" \
          --appName "${{ secrets.APP_NAME }}"
