name: Deploy to CapRover
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          # Retirons la configuration du cache qui cause l'erreur
          # cache: 'npm'

      - name: Debug Info
        run: |
          echo "Current directory:"
          pwd
          echo "Repository contents:"
          ls -la
          echo "Git branch:"
          git branch --show-current

      - name: Install CapRover CLI
        run: |
          npm install -g caprover
          caprover --version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:latest

      - name: Debug Before Deploy
        run: |
          echo "Deploying to URL: ${{ secrets.CAPROVER_URL }}"
          echo "App name: ${{ secrets.APP_NAME }}"
          echo "Docker image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:latest"

      - name: Deploy to CapRover
        env:
          APP_TOKEN: ${{ secrets.CAPROVER_APP_TOKEN }}
        run: |
          caprover deploy \
            --caproverUrl "${{ secrets.CAPROVER_URL }}" \
            --appToken "$APP_TOKEN" \
            --imageName "${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:latest" \
            --appName "${{ secrets.APP_NAME }}" \
            --skipUpdate
